### ISSUE TITLE
Functions Intro is written badly

### ISSUE THREAD

**Issue by jesseilev** [LaunchCodeEducation/thinkcspy#26]
https://runestone.launchcode.org/runestone/static/thinkcspy/Functions/functions.html

Should talk about examples *before* generalizing.

Should break up examples into smaller steps. First a non-DRY solution without a function, then a solution with a function, then a function that accepts an argument, etc

**Comment by seraries** [comment]
Easy fix--since drawSquare has already been demonstrated previously (see https://runestone.launchcode.org/runestone/static/thinkcspy/PythonTurtle/IterationSimplifiesourTurtleProgram.html) as individual steps outside of a function--is to start by showing this chapter's example activeCode of drawSquare before detailed talk about functions in general. Maybe first review non-encapsulated code that draws a square as a reminder of what we've done previously.

**Comment by seraries** [comment]
Fixed
